-- 스키마 정본: schema.sql. V1__foundation.sql은 이 파일의 바이트 동일 Flyway 배포 복제본이다.
-- Spring SQL 초기화는 spring.sql.init.mode=never로 설정하고 Flyway만 DDL을 실행한다.
-- 운영 위치: classpath:db/migration. local만 classpath:db/local을 추가한다.
-- 적용된 V1은 변경하지 않는다. 후속 변경은 새 버전 migration과 정본에 함께 반영한다.
-- OQ-001: organization은 원천 조회 전용이다. overlay 및 organization_relationship_history는 생성하지 않는다.
-- REQ-010 이력 요구는 유지하되 승인 후 별도 migration으로 저장 경계를 구현한다.
-- OQ-002: 감사 테이블/트리거를 발명하지 않는다. 메타 일시는 전후값 추적 완료 증거가 아니다.
-- OQ-DATA-004: 상태/사용여부/보직 구분은 TEXT NULL, 기본값 및 CHECK enum 없음.
-- advisory AGENTS의 CODE:한국어명 상태 COMMENT 규칙은 미승인 값 발명 금지 계약과 충돌한다.
-- 따라서 해당 COMMENT는 승인 대기 사유를 기록하며 허용값 목록을 발명하지 않는다.
-- PK/login_id 유일성 외 업무 UK, XOR, 날짜 비교, 계층 순환 제약은 승인 전 추가하지 않는다.
-- FK는 참조 보존을 위해 기본 NO ACTION이며 CASCADE는 없다. 미정 필수 여부는 NULL 허용한다.
-- 생성 메타는 DB 서버 기본값, 수정 메타는 애플리케이션이 UPDATE마다 CURRENT_TIMESTAMP로 갱신한다.

CREATE TABLE IF NOT EXISTS organization (
    organization_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_code TEXT,
    organization_name TEXT,
    organization_type TEXT,
    parent_organization_id BIGINT REFERENCES organization (organization_id),
    effective_start DATE,
    effective_end DATE,
    use_status TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
COMMENT ON TABLE organization IS 'KORUS 합성 원천 조직·계층·적용기간 스냅샷. 관리 API는 조회 전용이며 관계 쓰기는 OQ-001 승인 대기다.';
COMMENT ON COLUMN organization.organization_id IS '서버 생성 조직 PK; 외부 참조 컬럼이 아니다.';
COMMENT ON COLUMN organization.organization_code IS '원천 조직코드; 업무 유일성 미승인으로 UK 없음.';
COMMENT ON COLUMN organization.organization_type IS '조직 구분 값 집합 미승인; TEXT NULL로 보존한다.';
COMMENT ON COLUMN organization.use_status IS 'OQ-DATA-004 승인 대기: 허용값 미정, NULL은 비활성을 뜻하지 않는다.';
CREATE INDEX IF NOT EXISTS ix_organization_code ON organization (organization_code);
CREATE INDEX IF NOT EXISTS ix_organization_parent_period
    ON organization (parent_organization_id, effective_start, effective_end);

CREATE TABLE IF NOT EXISTS korus_personnel_snapshot (
    personnel_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_number TEXT,
    person_name TEXT,
    organization_id BIGINT REFERENCES organization (organization_id),
    job_grade TEXT,
    employment_status TEXT,
    retirement_date DATE,
    last_synced_at TIMESTAMPTZ,
    use_status TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
COMMENT ON TABLE korus_personnel_snapshot IS 'PersonnelInformationPort의 KORUS 교직원 원천 스냅샷. 관리 API에서 원천 인사정보를 수정하지 않는다.';
COMMENT ON COLUMN korus_personnel_snapshot.personnel_id IS '서버 생성 스냅샷 PK; 외부 참조 컬럼이 아니다.';
COMMENT ON COLUMN korus_personnel_snapshot.employment_status IS 'OQ-DATA-004 승인 대기: 재직상태 허용값 미정, TEXT NULL로 보존한다.';
COMMENT ON COLUMN korus_personnel_snapshot.use_status IS 'OQ-DATA-004 승인 대기: 허용값 미정, NULL은 비활성을 뜻하지 않는다.';
COMMENT ON COLUMN korus_personnel_snapshot.last_synced_at IS '원천 스냅샷 공급자가 동기화 시 기록한다. 로컬 합성 시드는 실제 외부 동기화를 뜻하지 않는다.';
CREATE INDEX IF NOT EXISTS ix_personnel_employee_number ON korus_personnel_snapshot (employee_number);
CREATE INDEX IF NOT EXISTS ix_personnel_name ON korus_personnel_snapshot (person_name);
CREATE INDEX IF NOT EXISTS ix_personnel_organization_grade_status
    ON korus_personnel_snapshot (organization_id, job_grade, employment_status);

CREATE TABLE IF NOT EXISTS user_account (
    account_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    login_id TEXT,
    password_hash TEXT,
    personnel_id BIGINT REFERENCES korus_personnel_snapshot (personnel_id),
    use_status TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_user_account_login_id UNIQUE (login_id)
);
COMMENT ON TABLE user_account IS '로컬 내부 인증 계정과 시스템 사용여부를 보존한다. 비밀번호 검증값만 저장하고 API 응답 및 추적에 노출하지 않는다.';
COMMENT ON COLUMN user_account.account_id IS '서버 생성 내부 계정 PK; 외부 참조 컬럼이 아니다.';
COMMENT ON COLUMN user_account.login_id IS '기술 로그인 식별자 UK; NULL 필수 여부는 OQ-DATA-001 승인 대기다.';
COMMENT ON COLUMN user_account.password_hash IS '로컬 BCrypt 검증값; 평문 비밀번호 저장·응답 금지. 운영 알고리즘 정책은 OQ-006이다.';
COMMENT ON COLUMN user_account.use_status IS 'OQ-DATA-004 승인 대기: 허용값 미정, NULL을 로그인 차단으로 해석하지 않는다.';
CREATE INDEX IF NOT EXISTS ix_account_personnel ON user_account (personnel_id);
CREATE INDEX IF NOT EXISTS ix_account_use_status ON user_account (use_status);

CREATE TABLE IF NOT EXISTS organization_user_mapping (
    mapping_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    personnel_id BIGINT REFERENCES korus_personnel_snapshot (personnel_id),
    organization_id BIGINT REFERENCES organization (organization_id),
    position_name TEXT,
    use_status TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
COMMENT ON TABLE organization_user_mapping IS '원천 교직원의 보직 및 조직 매핑 스냅샷. 관리 API 조회 전용이며 자동 역할 부여의 근거로 사용하지 않는다.';
COMMENT ON COLUMN organization_user_mapping.mapping_id IS '서버 생성 보직 매핑 PK; 외부 참조 컬럼이 아니다.';
COMMENT ON COLUMN organization_user_mapping.use_status IS 'OQ-DATA-004 승인 대기: 허용값 미정, NULL은 비활성을 뜻하지 않는다.';
CREATE INDEX IF NOT EXISTS ix_mapping_personnel ON organization_user_mapping (personnel_id);
CREATE INDEX IF NOT EXISTS ix_mapping_organization ON organization_user_mapping (organization_id);

CREATE TABLE IF NOT EXISTS role (
    role_code TEXT PRIMARY KEY,
    role_name TEXT,
    purpose TEXT,
    assignment_criteria TEXT,
    default_data_scope TEXT,
    use_status TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_role_code CHECK (role_code IN ('R01', 'R02', 'R03', 'R04', 'R05', 'R06', 'R07', 'R08', 'R09'))
);
COMMENT ON TABLE role IS 'R01부터 R09까지의 역할 정의와 목적·부여 기준·기본 데이터 범위를 보존한다. 역할명 변경 시 역할코드는 유지한다.';
COMMENT ON COLUMN role.role_code IS '원문 확정 R01..R09 TEXT PK; 미정 상태 enum과 구별한다.';
COMMENT ON COLUMN role.default_data_scope IS '기본 범위 설명값; 범위 값 집합 및 접근 효력은 OQ-004 승인 대기다.';
COMMENT ON COLUMN role.use_status IS 'OQ-DATA-004 승인 대기: 허용값 미정, NULL은 비활성을 뜻하지 않는다.';

CREATE TABLE IF NOT EXISTS user_role (
    assignment_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id BIGINT REFERENCES user_account (account_id),
    role_code TEXT REFERENCES role (role_code),
    approver_id BIGINT REFERENCES user_account (account_id),
    valid_start DATE,
    valid_end DATE,
    assignment_source TEXT,
    assignment_status TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
COMMENT ON TABLE user_role IS '사용자 역할 부여와 승인자·유효기간·부여 구분을 보존한다. 승인자 자동 대입, 만료 및 회수 상태 정책은 승인 대기다.';
COMMENT ON COLUMN user_role.assignment_id IS '서버 생성 역할 부여 PK; 외부 참조 컬럼이 아니다.';
COMMENT ON COLUMN user_role.assignment_source IS 'OQ-DATA-004 승인 대기: 보직 기반·수동 표현값 미정, 자동 역할 생성 없음.';
COMMENT ON COLUMN user_role.assignment_status IS 'OQ-DATA-004 승인 대기: 허용값 미정, NULL을 회수·미부여로 해석하지 않는다.';
COMMENT ON COLUMN user_role.approver_id IS '명시 승인자 계정 FK; 처리자를 자동 복사하지 않는다. 시드 승인자 미정은 NULL이다.';
COMMENT ON COLUMN user_role.valid_start IS '유효 시작일 기록; OQ-005 승인 전 인증 효력을 추정하지 않는다.';
COMMENT ON COLUMN user_role.valid_end IS '유효 종료일 기록; OQ-005 승인 전 NULL 또는 날짜로 만료를 추정하지 않는다.';
CREATE INDEX IF NOT EXISTS ix_user_role_account_role ON user_role (account_id, role_code);
CREATE INDEX IF NOT EXISTS ix_user_role_role ON user_role (role_code);
CREATE INDEX IF NOT EXISTS ix_user_role_approver ON user_role (approver_id);
CREATE INDEX IF NOT EXISTS ix_user_role_account_period ON user_role (account_id, valid_start, valid_end);

CREATE TABLE IF NOT EXISTS menu (
    menu_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_menu_id BIGINT REFERENCES menu (menu_id),
    display_order INTEGER,
    menu_name TEXT,
    screen_id TEXT,
    url TEXT,
    icon TEXT,
    business_category TEXT,
    description TEXT,
    use_status TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
COMMENT ON TABLE menu IS '대메뉴·중메뉴·화면의 계층과 실행정보를 보존한다. 로그인은 메뉴 밖 공개 진입점이며 이 테이블에 시드하지 않는다.';
COMMENT ON COLUMN menu.menu_id IS '서버 생성 메뉴 PK; 외부 참조 컬럼이 아니다.';
COMMENT ON COLUMN menu.screen_id IS 'UI 화면 레지스트리 식별 문자열 참조 의도; 관계형 FK 대상이 아니다. 그룹 메뉴는 NULL이다.';
COMMENT ON COLUMN menu.use_status IS 'OQ-DATA-004 승인 대기: 허용값 미정, NULL은 비활성을 뜻하지 않는다.';
CREATE INDEX IF NOT EXISTS ix_menu_parent_order ON menu (parent_menu_id, display_order);
CREATE INDEX IF NOT EXISTS ix_menu_screen ON menu (screen_id);

CREATE TABLE IF NOT EXISTS menu_permission (
    permission_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    menu_id BIGINT REFERENCES menu (menu_id),
    role_code TEXT REFERENCES role (role_code),
    organization_id BIGINT REFERENCES organization (organization_id),
    account_id BIGINT REFERENCES user_account (account_id),
    access_allowed BOOLEAN,
    use_status TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
COMMENT ON TABLE menu_permission IS '역할·조직·사용자 대상의 계층별 메뉴 접근 설정을 보존한다. 충돌 합성 OQ-003 및 대상 XOR·중복 정책은 승인 대기다.';
COMMENT ON COLUMN menu_permission.permission_id IS '서버 생성 권한 PK; 외부 참조 컬럼이 아니다.';
COMMENT ON COLUMN menu_permission.access_allowed IS '명시 접근 허용 BOOLEAN; NULL 기본 허용·거부 및 충돌 우선순위는 발명하지 않는다.';
COMMENT ON COLUMN menu_permission.use_status IS 'OQ-DATA-004 승인 대기: 허용값 미정, NULL은 비활성을 뜻하지 않는다.';
CREATE INDEX IF NOT EXISTS ix_permission_menu_role ON menu_permission (menu_id, role_code);
CREATE INDEX IF NOT EXISTS ix_permission_menu_organization ON menu_permission (menu_id, organization_id);
CREATE INDEX IF NOT EXISTS ix_permission_menu_account ON menu_permission (menu_id, account_id);

CREATE TABLE IF NOT EXISTS code_group (
    code_group_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id TEXT,
    group_name TEXT,
    description TEXT,
    managing_organization_id BIGINT REFERENCES organization (organization_id),
    use_status TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
COMMENT ON TABLE code_group IS '공통코드 묶음의 업무 그룹ID·명칭·설명·관리부서를 보존한다. 내부 PK와 업무 그룹ID를 분리하여 자식 참조를 유지한다.';
COMMENT ON COLUMN code_group.code_group_id IS '서버 생성 코드그룹 PK; 외부 참조 컬럼이 아니다.';
COMMENT ON COLUMN code_group.group_id IS '업무 그룹 식별자; FK 없는 업무 문자열이며 UK·외부 참조 갱신은 OQ-DATA-003 승인 대기다.';
COMMENT ON COLUMN code_group.use_status IS 'OQ-DATA-004 승인 대기: 허용값 미정, NULL은 비활성을 뜻하지 않는다.';
CREATE INDEX IF NOT EXISTS ix_code_group_group_id ON code_group (group_id);
CREATE INDEX IF NOT EXISTS ix_code_group_organization ON code_group (managing_organization_id);

CREATE TABLE IF NOT EXISTS detail_code (
    detail_code_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code_group_id BIGINT REFERENCES code_group (code_group_id),
    code_value TEXT,
    code_name TEXT,
    parent_detail_code_id BIGINT REFERENCES detail_code (detail_code_id),
    display_order INTEGER,
    additional_attributes JSONB,
    use_status TEXT,
    valid_start DATE,
    valid_end DATE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
COMMENT ON TABLE detail_code IS '그룹별 상세코드 계층·정렬·추가속성·사용여부·기간을 보존한다. 연계 매핑 속성 저장은 실제 외부 호출을 뜻하지 않는다.';
COMMENT ON COLUMN detail_code.detail_code_id IS '서버 생성 상세코드 PK; 외부 참조 컬럼이 아니다.';
COMMENT ON COLUMN detail_code.additional_attributes IS '추가속성 및 연계 코드 매핑 JSONB; 키·값 제약 미승인, 기본 객체를 강제하지 않는다.';
COMMENT ON COLUMN detail_code.use_status IS 'OQ-DATA-004 승인 대기: 허용값 미정, NULL은 비활성을 뜻하지 않는다.';
CREATE INDEX IF NOT EXISTS ix_detail_code_group_order ON detail_code (code_group_id, display_order);
CREATE INDEX IF NOT EXISTS ix_detail_code_parent ON detail_code (parent_detail_code_id);

CREATE TABLE IF NOT EXISTS session (
    session_id TEXT PRIMARY KEY,
    account_id BIGINT REFERENCES user_account (account_id),
    session_status TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
COMMENT ON TABLE session IS 'AuthenticationPort의 불투명 서버 생성 세션과 인증 계정 참조를 보존한다. 수명 정책은 미정이며 로그아웃 후 인증 종료는 서비스 책임이다.';
COMMENT ON COLUMN session.session_id IS '예측 불가능한 서버 생성 세션 TEXT PK; 외부 FK 대상이 아니며 API JSON·로그에 노출하지 않는다.';
COMMENT ON COLUMN session.session_status IS 'OQ-DATA-004 승인 대기: 허용값·수명 미정, NULL을 만료 또는 미인증으로 추정하지 않는다.';
CREATE INDEX IF NOT EXISTS ix_session_account_status ON session (account_id, session_status);
